### ISSUE TITLE
How to compile on Mac

### ISSUE THREAD

**Issue by atv2016** [aybassiouny/OpenFaceCpp#1]
Seems to miss unitttest lib.ld: warning: directory not found for option '-L/Users/alefveld/Downloads/OpenFaceCpp-master/Lib/unittest-cpp/builds'
ld: library not found for -lUnitTest++

**Comment by atv2016** [comment]
I got it to compile by removing the builds directory and editing the cmakeLists.txt to point at the directory before that. But now i get:

Daedalus:OpenFaceCpp-master alefveld$ ./OpenFaceCpp 
/Users/alefveld/Downloads/OpenFaceCpp-master/NativeDLib.cpp:239:1: error: Failure in shapePredictor: Unhandled exception: Unable to open shape_predictor_68_face_landmarks.dat for reading.
/Users/alefveld/Downloads/OpenFaceCpp-master/NativeDLib.cpp:247:1: error: Failure in getlargestBB: Unhandled exception: Unable to open file: sample.jpg
FAILURE: 2 out of 4 tests failed (2 failures).
Test time: 1.31 seconds.

Any help would be appreciated.

**Comment by atv2016** [comment]
I don't see to have those files?

**Comment by aybassiouny** [comment]
Hello, you can find the model in the original repo

**Comment by atv2016** [comment]
Found them.

I don’t get any output though, it finishes all tests successfully (just added a sample.jpg from myself) but then it exits.

Should the program start ?

**Comment by aybassiouny** [comment]
I made a lot of fixes, please retry and let me know. End result should be in representation.txt at the same folder.

**Comment by aybassiouny** [comment]
I will close the issue till further notice.
