### ISSUE TITLE
Gpu face_detection

### ISSUE THREAD

**Issue by raaka1** [aybassiouny/OpenFaceCpp#12]
Hey 

I am using OpenCV   gpu::GpuMat  for face detection which is much more accurate.
can i use use   gpu::GpuMat  instead of dlib ? does it make any difference.

**Comment by aybassiouny** [comment]
Hi @raaka1, Interesting suggestion. It should make no difference - at least for face detection. dlib is used for a couple other things but I reckon they all can be done with OpenCV as well.

**Comment by raaka1** [comment]
Hi Aybass, can you share you email, i would like to talk in private

**Comment by raaka1** [comment]
getAffineTransform in Native.cpp

i am little confused by the code, is the objective to get 2*3 Matrix of the cropped images right ?
using http://docs.opencv.org/2.4/doc/tutorials/imgproc/imgtrans/warp_affine/warp_affine.html

**Comment by aybassiouny** [comment]
the point from this part of the code is to make the face forward looking to ease normalize recognition step. So, in case the resulting detection rectangle was skewed, this makes it straight. Of course this is as far as I remember, you can review original code here as well https://github.com/cmusatyalab/openface/blob/master/openface/align_dlib.py.

**Comment by raaka1** [comment]
i am trying to implement  wra affine on GPU 

I am stuck at this point, i am using GPU detect multiscale and trying to recognize all the faces 

                    ```
    ostringstream filename_cv_a;
                                filename_cv_a << i << faces[i] << ".jpg";
                                croppedFaceImage = image_cv4t(faces[i]).clone();


                                //    gpu::warpAffine(faceBuf_gpu[i],wrapedImg,,faceBuf_gpu[i].size());
                                //  imwrite(filename_cv_a.str(), croppedFaceImage);
                                //

                                Point2f srcTri[3];
                                Point2f dstTri[3];

                                cv::Mat warp_mat( 2, 3, CV_32FC1 );
                                warp_dst = Mat::zeros( croppedFaceImage.rows, croppedFaceImage.cols, croppedFaceImage.type() );
                                srcTri[0] = Point2f( 0,0 );
                                srcTri[1] = Point2f( croppedFaceImage.cols - 1, 0 );
                                srcTri[2] = Point2f( 0, croppedFaceImage.rows - 1 );

                                dstTri[0] = Point2f( croppedFaceImage.cols*0.0, croppedFaceImage.rows*0.33 );
                                dstTri[1] = Point2f( croppedFaceImage.cols*0.85, croppedFaceImage.rows*0.25 );
                                dstTri[2] = Point2f( croppedFaceImage.cols*0.15, croppedFaceImage.rows*0.7 );
                                warp_mat = getAffineTransform( srcTri, dstTri );


```

**Comment by raaka1** [comment]
This is way faster, if you want to use multiple faces 

```
cv::gpu::CascadeClassifier_GPU cascade_gpu;       
   cascade_gpu.load("haarcascade_frontalface_alt.xml");
      gpu::GpuMat faceBuf_gpu, GpuImg;
                GpuImg.upload(grayImg);

                int detectionNumber = cascade_gpu.detectMultiScale(GpuImg, faceBuf_gpu);

    cascade_gpu.release();
```

**Comment by aybassiouny** [comment]
Sounds good. Unfortunately we don't have a gpu flag is not supported yet here. Will add this excerpt whenever we do. Thanks!
