### ISSUE TITLE
Is it possible now using OpenFaceCpp for face recognotion?

### ISSUE THREAD

**Issue by alexkutsan** [aybassiouny/OpenFaceCpp#13]
I I can see in repository models folder, but all models are lua files, and I am confused reading it. 
It is just some amount of magic numbers. Probably it is coeficients of pre trained neural network.
Can I use pre trined neural network in C++? 
I would like pre trained network, finish thaining with specific faces and then recognize it. Is this softweare ready for it or no? If no, probably I can try to implement missing parts my self, but it is hard to get into without help.

**Comment by ashokbugude** [comment]
Were you able to implement face recognition using openfacecpp or please provide the link from where you could implement it

**Comment by aybassiouny** [comment]
Hi, this is the whole purpose from this repo :) Unfortunately I am no ML whiz, so other than using pre-trained networks I am of no use. Please consult original repo/paper for how to train new networks.
