### ISSUE TITLE
Feature vector is Empty

### ISSUE THREAD

**Issue by athulsnambiar** [aybassiouny/OpenFaceCpp#14]
I tried to run OpenFaceCpp like this,

```
$./OpenFaceCpp OpenFaceConfig.xml aaa.jpg
```

And this is the output

```
Launching th_emulator.exe openface_server.lua -model ../models/openface/nn4.v1.t7 -imgDim 96
listening ...
Received: 
Received result feature vector of size : 0
```

I have downloaded all models and OpenFaceConfig.xml is set properly

Could you please suggest how to solve this issue?

**Comment by macarran** [comment]
@athulsnambiar did you figure this out by any chance? I'm getting the same result.

**Comment by ALojdl** [comment]
@macarran  @athulsnambiar I got same result, but it seems that no LUA server errors are handled properly. So first try to run server with command being printed when OpenFaceCpp is started.

**Comment by nchandna** [comment]
@athulsnambiar 
what is meant by "OpenFaceConfig.xml is set properly" and where is "aaa.jpg" ,is it model data or your training image.

please provide useful steps for running the library (after downloading model data and binary is build) if you was able to run the library.

**Comment by nchandna** [comment]
@ALojdl @macarran 
can you please provide useful steps if you were able to run the library and able to test the library.

how can i train the engine with my specified set of images and then match against them.

**Comment by ghost** [comment]
I have the same problem...

**Comment by kelvinquan** [comment]
Hi, 

Are there any solutions to the above-mentioned issue?

**Comment by ramanjotkaur90** [comment]
Hi ,

Can anyone please update the solution to this problem

**Comment by ramanjotkaur90** [comment]
@aybassiouny please suggest

**Comment by aybassiouny** [comment]
This is a major issue that occurred after the move to Windows - unfortunately I am just realizing it. I hope to get if fixed in the next couple of weeks by moving to PyTorch probably. Sorry about delay guys.

**Comment by aybassiouny** [comment]
This is addressed on the latest commit. @athulsnambiar could you retry please?
