### ISSUE TITLE
Installation problem without cuda

### ISSUE THREAD

**Issue by mhaghighat** [aybassiouny/OpenFaceCpp#15]
I wonder if there is a way to install this on a virtual machine with no GPU. The Python version (from the CMU [OpenFace](https://github.com/cmusatyalab/openface) library) works fine on the same machine, but I cannot install this one.
 
Thanks for the help.

**Comment by ashokbugude** [comment]
were you able to install without gpu ?

**Comment by aybassiouny** [comment]
I am actually testing mainly on a machine without GPU, could you report the installation issue exactly?
