### ISSUE TITLE
how would i use this with a web camera instead of a single file?

### ISSUE THREAD

**Issue by atv2016** [aybassiouny/OpenFaceCpp#16]
maybe using opencv?

on https://medium.com/@ageitgey/machine-learning-is-fun-part-4-modern-face-recognition-with-deep-learning-c3cffc121d78#.rai5axxap they show a webcam doing predictions.

**Comment by aybassiouny** [comment]
This would need a change in source file, OpenCV should easily do this. You could use main.cpp as an example to mimic
