### ISSUE TITLE
build fails on mac QTKit not found?

### ISSUE THREAD

**Issue by atv2016** [aybassiouny/OpenFaceCpp#17]
[ 78%] Linking CXX static library ../../lib/libopencv_shape.a
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: ../../lib/libopencv_shape.a(precomp.cpp.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: ../../lib/libopencv_shape.a(precomp.cpp.o) has no symbols
[ 78%] Built target opencv_shape
/Users/alefveld/.hunter/_Base/d073cc0/f7e04db/084fc85/Build/OpenCV/Source/modules/videoio/src/cap_qtkit.mm:46:9: fatal error: 'QTKit/QTKit.h' file not found
#import <QTKit/QTKit.h>
        ^
1 error generated.
make[5]: *** [modules/videoio/CMakeFiles/opencv_videoio.dir/src/cap_qtkit.mm.o] Error 1
make[5]: *** Waiting for unfinished jobs....
make[4]: *** [modules/videoio/CMakeFiles/opencv_videoio.dir/all] Error 2
make[4]: *** Waiting for unfinished jobs....
[ 78%] Linking CXX static library ../../lib/libopencv_photo.a
[ 78%] Built target opencv_photo
make[3]: *** [all] Error 2
make[2]: *** [OpenCV-Release-prefix/src/OpenCV-Release-stamp/OpenCV-Release-install] Error 2
make[1]: *** [CMakeFiles/OpenCV-Release.dir/all] Error 2
make: *** [all] Error 2

**Comment by navneet1083** [comment]
were you able to fix this out. I am also getting the same error in Ubuntu.

**Comment by aybassiouny** [comment]
Unfortunately project is only maintained on Windows right now. Please feel free to contribute Ubuntu build if possible :)  Package's source should be pretty portable
