### ISSUE TITLE
create_pipe() is not find.

### ISSUE THREAD

**Issue by zhongzhiwei1987** [aybassiouny/OpenFaceCpp#18]
When we use cmake --build , I find opencv and boostprocess can not do.
while when I just use OpenFaceCpp-master/src/main.cpp ,  I used boost1.5.7 and boostprocess, that is not find create_pipe().

**Comment by TZVIh** [comment]
hey,
did you find a solution?

**Comment by aybassiouny** [comment]
Hey could you try the new version again? Please make sure to do "git submodule update --init" as well.

**Comment by aybassiouny** [comment]
I will assume this issue is resolved.
