### ISSUE TITLE
Build fails with SHA1 error

### ISSUE THREAD

**Issue by GlowTube** [aybassiouny/OpenFaceCpp#22]
I get this error repeatedly.  After trying about 20 times it's difficult to believe that the downloads themselves are corrupt, as the SHA1 values are consistent.

Has anyone successfully compiled this package recently on Linux?  Is there a way to turn off the SHA1 comparison?

-- SHA1 hash of
    /home/tcc/.hunter/_Base/Download/OpenCV/3.0.0-p6/228124c/3.0.0-p6.tar.gz
  does not match expected value
    expected: '228124cf6076d9da62f1a9a357e350f3e43f81d0'
      actual: 'bf51cf6fff52da81d7756c15cc878096813b256c'

**Comment by quanweikikai** [comment]
same issue need to be solved...

**Comment by TomGrivaud** [comment]
I also have the same issue...

**Comment by quanweikikai** [comment]
Is it because someone changed the files that make the SHA1 different?

Anyone would like to share a copy?

**Comment by aybassiouny** [comment]
I think this is due to a new change that mde around that period. I just changed versions of hunter packages, could you try to clean source and clone the repo again? Let me know if there are still problems.
