### ISSUE TITLE
Build Error 'INT32': redefinition

### ISSUE THREAD

**Issue by sGambolati** [aybassiouny/OpenFaceCpp#24]
Hi!

I'm very newbie in this project and I'm trying to build the projects and get the following error both the console with cmake --build . and build from Visual Studio.

> Error C2371 'INT32': redefinition; different basic types dlib (C:\Program Files (x86)\Windows Kits\10\Include\10.0.15063.0\shared\basetsd.h)

I'm using Visual Studio 2017 on Windows 10.

Any idea or anything i'm missing?

Thanks!

**Comment by srasilla** [comment]
Hi,

I have managed to compile only by adding a comment to the line:
.... \ jmorecfg.h

/ * INT32 must hold at least signed 32-bit values. * /

#ifndef XMD_H / * X11 / xmd.h correctly define INT32 * /
#ifndef _BASETSD_H_ / * Microsoft defines it in basetsd.h * /
#ifndef _BASETSD_H / * MinGW is slightly different * /
#ifndef QGLOBAL_H / * Qt define it in qglobal.h * /
// typedef long INT32; <-------------------- HERE COMMENT !!
...
..
.

**Comment by aybassiouny** [comment]
Hey, we just consumed newer versions of our dependencies. Error should disappear now.
