### ISSUE TITLE
Execution problem

### ISSUE THREAD

**Issue by gaudinjonas** [aybassiouny/OpenFaceCpp#27]
When I try to execute ./OpenFaceCpp I pass two argument : the config file and a picture.
But I have this error : 
"Invalid argument: Unable to process file.
Launching th_emulator.exe openface_server.lua -model Models/openface/nn4.small2.v1 -imgDim 96
Failed to process image .Caught exception std::exception"

Do you have an idea ?

Thanks

**Comment by seungyoungshin** [comment]
I have a same problem.
I had copy all of model folder from original repo.
After that,  First error message has gone.("Invalid argument: Unable to process file.)
However, other two message are remain.

**Comment by aybassiouny** [comment]
This is related to not having downloaded models specified in OpenFaceConfig.xml. I have updated package with better error messages.
