### ISSUE TITLE
OpenFaceCpp/Lib/tinyxml2    does not contain a CMakeLists.txt file.

### ISSUE THREAD

**Issue by adv-ai-tech** [aybassiouny/OpenFaceCpp#30]
@aybassiouny 

I am getting this error. 
`home/...../OpenFaceCpp/Lib/tinyxml2 does not contain a CMakeLists.txt file`

I'm not able to figure out why. Can someone please point out the issue?
I have executed the following commands
```
root$
git clone http:...
mkdir build
cmake ..
```

Just to confirm, This runs on Ubuntu also right?

**Comment by aybassiouny** [comment]
you need to do `cd build` first before `cmake ..`?  Also make sure to clone the sub modules too.

**Comment by 10424142** [comment]
I also got the same problem.
I don't know why but dlib and TinyXML2 folder in Lib will be empty in downloaded file.

It will be solved after download dlib(https://github.com/davisking/dlib) and TinyXML2( https://github.com/leethomason/tinyxml2) and unzip to  corresponding folder.

Forgive for my poor English. QQ
