### ISSUE TITLE
Space required by OpenFaceCpp

### ISSUE THREAD

**Issue by pachla195882** [aybassiouny/OpenFaceCpp#31]
Hey, I would like to install OpenFaceCpp on RaspberryPi. My question is how much space does OpenFaceCpp require? I removed all unnecessary software, but 3 GB is not enough. I just started wondering whether OpenFaceCpp really requires such big amount of space, or I am facing some kind of a bug? Thanks

**Comment by aybassiouny** [comment]
Hey, you only need the executable, config file, and models. Running torch will be the more challenging/space consuming part, but OpenFaceCpp on its own is not really space hungry.
