### ISSUE TITLE
No run_tests.cpp file.

### ISSUE THREAD

**Issue by RodolfoSan** [aybassiouny/OpenFaceCpp#4]
When finally building the project, there's no run_tests file. 

Any help? Or am I missing something?

**Comment by aybassiouny** [comment]
Hello, please use latest code version and erase earlier ones.

**Comment by mousmita** [comment]
Hi Ahmed, 
Thanks for your great work.

What should be content of run_tests file?
Further please let me know about the representation.txt in
TorchWrap("models/openface/nn4.small2.v1.t7", 96, "representation.txt")

I am unable to proceed.

Thanks in advance
Mousmita

**Comment by Hardold** [comment]
Does this program realize the function of face recognition?

**Comment by aybassiouny** [comment]
Fixed in latest commit. 

@mousmita representation.txt was the output file where resulting feature vector for face is exported
