### ISSUE TITLE
tw.forwardImage is not returnung the vector in simClassification.cpp 

### ISSUE THREAD

**Issue by mousmita** [aybassiouny/OpenFaceCpp#5]
Hi Ahmed,
I am getting segmentation fault (core dumped).
So the code reaches all the way to the following line before segfaulting.
feat(0,i) = train1rep[i];
  It segfaults here because train1rep was never initialized by tw. Problem is that tw.forwardImage is not returning the vector. I saw that the openface_server.lua never gets the path of temp_aligned.jpg properly. 

Can you please tell me how to solve the issue. 

Thanks
Mousmita

**Comment by pobei** [comment]
i am now facing the same problem....have you solved it ,i think it might because that the subprocess that runs the network do not work ....,by the way ,have you solved it ?

**Comment by pobei** [comment]
hi mousmita 
    now i am facing the same problem..i think it was because that the subprocess that runs the network does not work ...btw,have you solved it?

**Comment by aybassiouny** [comment]
This seems like a path issue to the image - or maybe something deeper. Could you rest using new commits?
