### ISSUE TITLE
windows user can not use torch.load('nn4.small2.v1.ascii.t7','ascii')

### ISSUE THREAD

**Issue by honghuCode** [aybassiouny/OpenFaceCpp#8]
![error](https://cloud.githubusercontent.com/assets/14934309/18031342/e8dd72f4-6d0e-11e6-8934-8d2df1e91600.jpg)

**Comment by aybassiouny** [comment]
Frankly I have not got this to work fully on windows yet. Did you try the original python repo? This looks like lua stuff so they should have the same thing.
